#!/usr/bin/env bash# Function to display DNS information for a subdomain
display_dns_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type="$(dig "$subdomain.$domain" +short -t ANY)"
    local destination="$(dig "$subdomain.$domain" +short | tr '\n' ' ')"

    if [ -z "$record_type" ]; then
        echo "The subdomain $subdomain does not exist."
    else
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

# Main script
if [ $# -eq 1 ]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        display_dns_info "$domain" "$subdomain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    display_dns_info "$domain" "$subdomain"
else
    echo "Usage: $0 <domain> [subdomain]"
fi
