#!/usr/bin/env bash
# Install nginx and configure redirection

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo '
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}
' > /etc/nginx/sites-available/default

service nginx reload
