#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a configuration file for the redirection
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Other server configurations
}
EOT

# Enable the new configuration
sudo ln -s /etc/nginx/sites-available/3-redirection /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx