#!/usr/bin/env bash

# Install nginx and configure custom HTTP response header

# Update package list
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create a custom nginx configuration file to set the response header
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_response_header.conf

# Reload Nginx to apply changes
sudo service nginx reload
