#!/usr/bin/env bash
# Update the package list and install HAProxy with the -y option for automatic yes to prompts

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 259884-web-01 52.91.123.176:80 check\n\tserver 259884-web-02 3.85.196.6:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart