#!/usr/bin/env bash
# Install HAProxy

# Update the system
sudo apt-get update -y

# Install HAProxy
sudo apt-get install haproxy -y

# Define backend servers
backend_servers=(
  "web-01 259884-web-01 54.175.198.8:80 check"
  "web-02 259884-web-02 52.86.56.129:80 check"
)

# Create the HAProxy configuration
haproxy_cfg="/etc/haproxy/haproxy.cfg"
echo "frontend http-in
  bind *:80
  default_backend servers

backend servers
  balance roundrobin" | sudo tee "$haproxy_cfg"

# Add backend server entries
for server_entry in "${backend_servers[@]}"; do
  echo "  server $server_entry" | sudo tee -a "$haproxy_cfg"
done

# Ensure HAProxy can be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy