#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 259884-web-01 52.23.245.46 check\n\tserver 259884-web-02 52.23.245.46 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart