#!/usr/bin/env bash

# Update the system
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Define backend server information (hostname and IP address)
backend_servers=(
  "web-01 259884-web-01"
  "web-02 259884-web-02"
)

# Create a custom response header configuration file
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_response_header.conf

# Remove existing symbolic link if it exists
sudo rm -f /etc/nginx/sites-enabled/default

# Create a new site configuration
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        include /etc/nginx/conf.d/custom_response_header.conf;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
    }
}' | sudo tee /etc/nginx/sites-available/custom_config

# Create a symbolic link to enable the new site
sudo ln -s /etc/nginx/sites-available/custom_config /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx

# Create a custom index.html for testing
echo 'This is web-02' | sudo tee /var/www/html/index.html

# Create a custom 404.html
echo 'This is a custom 404 page' | sudo tee /var/www/html/404.html

# Restart Nginx to apply the custom 404 page
sudo systemctl restart nginx
