#!/usr/bin/env bash
# Remove default Nginx config, link to default, validate, and restart Nginx if valid
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
