#!/usr/bin/env bash
# Remove the default Nginx configuration file, link to the default config, check configuration, and restart Nginx
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -t -q || exit 1
systemctl restart nginx