#!/usr/bin/env bash
# This script displays numbers and messages based on the loop iteration

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    counter=$((counter + 1))
done
