#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

# Create a backup of the original hosts file
cp /etc/hosts ~/hosts.new

# Use sed to modify the hosts file
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# Replace the original hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
